// .storybook/components/stories/VanillaFrameworkThemeProvider.tsx
import { useEffect } from "react";
import type { ThemeName } from "../../theme";
import { CLASS_MAP } from "./constants";

const VanillaFrameworkThemeProvider = ({
  theme,
  children,
}: {
  theme: ThemeName;
  children: React.ReactNode;
}) => {
  useEffect(() => {
    const vanillaClassName = CLASS_MAP[theme];
    document.documentElement.classList.add(vanillaClassName);
    return () => {
      document.documentElement.classList.remove(vanillaClassName);
    };
  }, [theme]);

  return children;
};

export default VanillaFrameworkThemeProvider;

// .storybook/decorators/VanillaFrameworkThemeProvider.svelte
<script lang="ts">
  import type { ThemeName } from "../theme";
  import { CLASS_MAP } from "./constants";
  import type { WithThemeFromSvelteProviderProps } from "./withThemeFromSvelteProvider.decorator";

  let { theme, children }: WithThemeFromSvelteProviderProps = $props();
  const vanillaClassName = $derived(CLASS_MAP[theme as ThemeName]);

  $effect(() => {
    document.documentElement.classList.add(vanillaClassName);
    return () => {
      document.documentElement.classList.remove(vanillaClassName);
    };
  });
</script>

{@render children?.()}
